### ISSUE TITLE
Terraform Build Azure: Plan Dry Run doesn't prompt for prefix

### ISSUE THREAD

**Issue by rejackson73** [hashicorp/field-workshops-terraform#13]
Going through the Terraform Build Azure track, the challenge for the 'Terraform Plan - Dry Run Mode' doesn't prompt the user for the prefix.  It looks like the prefix was already in the '.tfvars' file with a value of 'yourname.'  Removing this line from the .tfvars file causes the challenge to operate as expected.

**Comment by scarolan** [comment]
This is fixed now.
