### ISSUE TITLE
terraform-build-aws add output and add lines to provisioner

### ISSUE THREAD

**Issue by assareh** [hashicorp/field-workshops-terraform#17]
Great job on this! Some feedback from my run through

1. It seems like the **Add an Output** task could be more clear. When I arrived at this task the outputs.tf file contained:
`# Outputs file`
`output "catapp_url" {
  value = "http://${aws_instance.hashicat.public_dns}"
}`

and the task says 

> Add a second output for the public_dns of your web server. Name your output catapp_url.

But we can't add another output of the same name. 

2. For the **Use a Provisioner** task, the task is asking us to add two lines of code to the remote-exec provisioner block. However I found that those two lines were already in the main.tf.

**Comment by assareh** [comment]
also found a few typos, see track file. 
[track.yml.txt](https://github.com/hashicorp/field-workshops-terraform/files/3976055/track.yml.txt)

**Comment by assareh** [comment]
tried to create a branch and send a PR for the track.yml edits but either I don't know what I'm doing or I don't have proper access. :-D

**Comment by scarolan** [comment]
Hi @assareh 

The catapp url issue has been fixed, it reads like this now:
```
    Add a second output for the `public_ip` of your web server.

    Name your output `catapp_ip`.
```

commands are no longer pre-populated in the main.tf file

I also removed references to line numbers and just ask the user to CTRL-F in the file instead.
