### ISSUE TITLE
Various suggested improvements for Terraform OSS for Azure workshop

### ISSUE THREAD

**Issue by rberlind** [hashicorp/field-workshops-terraform#2]
Great workshops, @scarolan 
As discussed via Slack, here are some suggested improvements for the Terraform OSS for Azure workshop:

1) Slide 33: I am prompted to "press Enter", not to type "Y" for "Yes".  Also, the script seems to take a long time to respond to pressing Enter.  Eventually, the window the script was run in does go away.
2) Slide 37: I did not see a "Reload" button.
3) Slide 38: I was not prompted to select a default shell.
4) Slide 48 (and others): Since the Azure VM uses Terraform 0.12, "<computed>" should be changed to "(known after apply)".
5) Slide 52: You might want to say to set location in the tfvars file as reflected in slide 53. Some people might think you mean to change the default for location in variables.tf.  Of course, that will also work.
6) Slides 62 and 73: I find it strange that provider is listed twice.  I don't know how you built the graphs. Perhaps from `terraform graph`? Of coSlide urse, if that command really shows provider twice, then we should leave it alone.
7) Slide 87: when I do terraform plan after moving VM into vm.tf, I got indication saying that azurerm_mysql_firewall_rule.vault-mysql will be updated in-place.  That seems to be because of these lines:
end_ip_address      = "13.90.157.31" -> (known after apply)
start_ip_address    = "13.90.157.31" -> (known after apply)
Probably because they are set from a data source.  We could avoid that by adding this to that resource:
```
  lifecycle {
    ignore_changes = [start_ip_address, end_ip_address]
  }
```
8) Slide 94: This slide needs updating since the source in actual file is "files/" and destination is "/home/${var.admin_username}/"
9) Slide 95: This slide has inconsistencies with the actual code in the remote-exec provisioner.
10) Slide 97: This slide should probably say that "Provisioners can be run when resources are created or destroyed, but are not run when they are modified."  (However, note that one can force a provisioner to run again if it is in a null_resource by tainting the null_resource.)
11) Slide 100: remove reference to `terraform fmt` since it was covered in chapter 4, not chapter 5.
12) Slide 106: you have asterisk on "re-create" but no corresponding footnote (which is in the TF 101 course).  I suggest removing the asterisk.
13) I think this workshop should also cover modules.  (I know you cover them a bit in the context of the PMR in chapter 10 of the TFE workshop.) After moving the VM into a different vm.tf, we could move the database server into a separate module and load it from main.tf. 
14) It might also be worthwhile to discuss the count meta-argument and indicate that we could have deployed a cluster of 3 Vault servers by setting count on the VM to 3.
15) It might also be worthwhile to explore the `terraform state` commands, especially `terraform state list`.

**Comment by scarolan** [comment]
Intro to TF OSS on Azure has been ported to Instruqt.  We'll take some of the suggestions like adding meta count, and a section on modules.  Those can be addressed as separate feature requests on the new deck.
