### ISSUE TITLE
Firewall resource name in GCP intro lab should be variable.

### ISSUE THREAD

**Issue by malekai101** [hashicorp/field-workshops-terraform#268]
I've run the Intro to Terraform on GCP lab twice in the last two weeks.  Each time someone gets an error message about resources already existing.  After some troubleshooting, I think it is because the firewall being created is not using an interpolated name.   The GCP accounts that we are using are maybe re-used and something didn't get reaped in a previous session leaving an existing firewall with the same name out there.   This causes errors on the GCP side when someone provisions.

I fix it in the lab by having the student interpolate the name of the firewall resource with prefix variable.  All of the other resources used in the Hashicat app are using interpolated names.  We should probably interpolate the firewall name with the prefix variable too.

**Comment by scarolan** [comment]
This will also need to be fixed over in https://github.com/hashicorp/hashicat-gcp

**Comment by rberlind** [comment]
I fixed this in https://github.com/hashicorp/hashicat-gcp and in https://github.com/workshops-testbot/hashicat-gcp
