### ISSUE TITLE
Need to turn on auto speculative plans to see Terraform checks run on PRs

### ISSUE THREAD

**Issue by omkensey** [hashicorp/field-workshops-terraform#270]
The "Terraform Cloud on AWS" track (as well as the GCP and Azure versions of that track) refers to workspaces running checks in the following line of the track.yml file:

https://github.com/hashicorp/field-workshops-terraform/blob/37d94bff05d4f76bcb54697e69cb106fdfebe9f9/instruqt-tracks/terraform-cloud-aws/track.yml#L557

...but the default setting for "Automatic speculative plans" for the workspace is off, and it needs to be turned on before the checks will run.  Attendees should be directed at some convenient point to turn the option on prior to running the PR workflow.

**Comment by rberlind** [comment]
@omkensey : I was actually able to do the fixes pretty quickly.  Please check out the PR https://github.com/hashicorp/field-workshops-terraform/pull/271 and approve if you thinks it looks good.  In addition to giving new instructions in the assignment, I also modified an earlier solve script to set up the workspaces with the changes.

**Comment by rberlind** [comment]
Merged fix.

**Comment by omkensey** [comment]
Just got around to this and see it's already been merged, but in any case, LGTM.
