### ISSUE TITLE
Various suggested improvements for the TFE for Azure workshop

### ISSUE THREAD

**Issue by rberlind** [hashicorp/field-workshops-terraform#3]
Here are my suggested improvements for the TFE for Azure workshop.
1) We need to use Terraform Cloud in many places where Terraform Enterprise is used, in line with the current branding.
2) Slide 32: it would be more accurate to say that "Terraform Enterprise **uses** the same application" rather than saying it  **is** the same application.
3) Before slide 85, I think we should add a slide instructing the student to queue a manual run from the TFC UI. They will then see their push in exercise 6d trigger a new apply.
4) Slide 89: It turns out that doing `terraform destroy` against a VCS-backed workspace is not currently allowed with the CLI using the remote backend.  (In the same way that `terraform apply` is not allowed.) I actually filed https://app.asana.com/0/1118351459439625/1143346646216873 suggesting it should be allowed.  So, users at this point will have to add the CONFIRM_DESTROY variable set to 1 and then use the TFC UI to destroy
5) Also, the "Auto apply" setting in workspaces does not apply to doing a destroy with the "Queue destroy plan" button.  So, slides like 89 that mention using the UI to destroy should point out the need to confirm the apply on the triggered run.
6) Slide 99: The  user will often have to refresh view to see the commit on the new policy set in list of policy sets.
7) Slide 101: I suggest that before starting lab exercise 7 that students be told to queue a plan so that they can see the tags policy violated.  They can then start lab 7 to add their tag.  If we do this, slide 101 should then show a screenshot of the policy passing, not failing.
8) Slide 102: The solution should remind the student to commit and push their changes to their GitHub repo.
9) Slide 106: partner 1 step 5 should probably be more specific and indicate to click the radio button with "Create a new branch for this commit and start a pull request."
10) Slide 115: students will have to do git pull or equivalent VSC command before pushing since in lab exercise 8, they made changes to repo on GitHub website and merged to master.  You do have git pull on slide 116, but would be good to mention on slide 115 too in case students try to do it before moving on to slide 116.
11) Slide 115: resetting the environment should probably also include removing all variables from variables.tf except prefix and location and then removing anything but those from Terraform Variables in the workspace.

**Comment by scarolan** [comment]
great feedback. i'm going to copy this into the Asana task for the project owner.
