### ISSUE TITLE
Should be azure not AWS.

### ISSUE THREAD

**Issue by rgustafs** [hashicorp/field-workshops-terraform#308]
Congratulations, you are ready to start working with Terraform on AWS. We'll use the hashicat-azure example app in the rest of the challenges as you learn new Terraform skills.

**Comment by scarolan** [comment]
Where did you find this text, @rgustafs ?  I did a search across the whole repo but i only found this phrase in the AWS tracks:
<img width="630" alt="Screen Shot 2021-10-07 at 7 37 52 AM" src="https://user-images.githubusercontent.com/403332/136385491-ed4adedb-d45f-435b-bd80-58c1bf2e697b.png">

**Comment by rberlind** [comment]
Fixed in https://github.com/hashicorp/field-workshops-terraform/pull/309
