### ISSUE TITLE
Instruqt labs broken ?

### ISSUE THREAD

**Issue by BillyCallahan** [hashicorp/field-workshops-terraform#348]
Hi,
I'm trying to access [this](https://play.instruqt.com/hashicorp/tracks/terraform-intro-aws) Instruct lab but I keep getting a 404 Not Found. Do I need privileged access or is this not working anymore ?

**Comment by omkensey** [comment]
Instruqt labs are invite-only; if you got an invite link to one through signing up for one of our public workshops or from a HashiCorp employee then it would have provided you access for a limited time, but the invite would have expired eventually (there are two expirations: how long you can use the invite to add the track to your Study Room in Instruqt, and how long after you do that the track itself is accessible for; generally the first one is set to a week and the second one is set to 30 days).

If you got an invite and you're sure it's still valid,  make sure you're signed in to Instruqt with an account created with an e-mail address allowed to access the invite.  (Invite link access can be and often is limited to particular e-mails or e-mail domains.)

(If you're trying to go there based on a link to that URL somewhere in our product docs or other materials hosted on hashicorp.com, let me know where the link is so I can contact the correct folks to fix it.)

**Comment by BillyCallahan** [comment]
Thank you for this thorough response.
I'm giving a lecture about Terraform in a few weeks and stumbled upon this material. I thought I could use it to demonstrate how Terraform works to my students and give them hands-on practice.
Do you sometimes grant access to the platform or is that something you would consider ?
Or is there any other "official" way to provide them with this kind of experience ?

**Comment by omkensey** [comment]
(sorry for getting back to this late)

To the best of my knowledge we don't grant access to anybody outside HashiCorp except as part of scheduled workshops.  Apart from that, our Learn site uses embedded Instruqt tracks for some tutorials that people can access anytime, though I don't know off the top of my head if any of them are Terraform ones.  It might be worth looking through there to see if there's a live tutorial environment you can access for what you're looking for.
