### ISSUE TITLE
Terraform Cloud on AWS v2 bug

### ISSUE THREAD

**Issue by chosam2** [hashicorp/field-workshops-terraform#370]
Hello @gcastill0.
While I was doing a "[Terraform Cloud on AWS v2](https://play.instruqt.com/hashicorp/tracks/terraform-cloud-aws-v2)" workshop, I got the following error reported by an attendee.

Intermittently in chapter **"Safekeeping Your Terraform State"** The following error occurs.

- Instruqt UI
![img](https://raw.githubusercontent.com/hyungwook0221/img/main/uPic/FdJ6BU.jpg)

- TFC UI
![img](https://raw.githubusercontent.com/hyungwook0221/img/main/uPic/VYPeJd.jpg)

- Error Message

`
Preparing the remote apply...
To view this run in a browser, visit:
https://app.terraform.io/app/hyungwook/hashicat-aws/runs/run-sxsLetCUhWeXsjbA
...(skip)`

`Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded`

**Comment by omkensey** [comment]
That's showing output from a remote run -- at that point in the workshop, the execution mode of the workspace should still be "local" which would use the cloud credentials embedded in the local Instruqt shell.  Was this workspace already existing prior to the workshop (or was its execution mode changed manually)?

**Comment by chosam2** [comment]
> That's showing output from a remote run -- at that point in the workshop, the execution mode of the workspace should still be "local" which would use the cloud credentials embedded in the local Instruqt shell. Was this workspace already existing prior to the workshop (or was its execution mode changed manually)?

@omkensey Thank you for your prompt response.
![img](https://raw.githubusercontent.com/hyungwook0221/img/main/uPic/IvQPtk.jpg)

I think your prediction is correct. Probably because the workspace variable created in the previous lab remained, it seems to have had an impact!

I have an additional question Can I add this to that thread?

**Comment by gcastill0** [comment]
This error message indicates the AWS variables are incorrect. The Principal Account credentials are expressed in TFC variable set called `Cloud Credentials`. Navigate to ORG -> Settings - Variable Sets and modify the `Cloud Credentials` variables with the appropriate content.

**Comment by hyungwook0221** [comment]
@gcastill0  Thank you for the reply.
`cd /root/terraform-cloud && terraform destroy --auto-approve` command is helpful for me.

This question was solved with the help of @omkensey and @omkensey.

I will close the issue.
Thank you.
