### ISSUE TITLE
Problem with TFE Azure workshop: Exercise 10a

### ISSUE THREAD

**Issue by rberlind** [hashicorp/field-workshops-terraform#4]
I got  the following error during apply:

```
Terraform v0.12.9
Initializing plugins and modules...
2019/10/07 01:14:15 [DEBUG] Using modified User-Agent: Terraform/0.12.9 TFC/3bcf15d045
module.web_app_container.azurerm_app_service_plan.main[0]: Creating...

Error: Error creating/updating App Service Plan "roger-plan" (Resource Group "roger-workshop"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Exceeded the limit of 1 free tier linux server farm per subscription." Details=[{"Message":"Exceeded the limit of 1 free tier linux server farm per subscription."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"11027","Message":"Exceeded the limit of 1 free tier linux server farm per subscription.","MessageTemplate":"Exceeded the limit of 1 free tier linux server farm per subscription.","Parameters":[]}}]

  on .terraform/modules/web_app_container/main.tf line 7, in resource "azurerm_app_service_plan" "main":
   7: resource "azurerm_app_service_plan" "main" {
```

That occurred for me both in centralus and in eastus.  I was working on a weekend when I don't think there would have been other "students" doing the lab.

Do we know if any students have been able to successfully complete this exercise?  Do we need to increase any limits on our Azure account?

Also, it is worth noting that the module will not work if the resource group has not already been created (since it finds it with a data source).  This is fine if the student follows the sequence in the slides.  But if they do a destroy against the workspace and then try to do an apply, it will fail.  To work around that, I had to remove the module and output, do my apply to create the resource group, add the module and output back, and then do a second apply.

**Comment by scarolan** [comment]
The module we're using has a bug in it that causes it to require an existing resource group.  It also seems to have problems with destroys.  I'd consider completely replacing it with another module or building our own.

https://github.com/innovationnorway/terraform-azurerm-web-app-container/issues/18
