### ISSUE TITLE
Lab 1: Moving In - no "Open Folder" option

### ISSUE THREAD

**Issue by vaficionado** [hashicorp/field-workshops-terraform#5]
It's actually just File > Open and then you select the folder from there. Or you can use the 'Open Folder' button on the Files tab (not open by default) - but for some reason my editor won't open a folder no matter what I click. It works fine on my local desktop, something is odd in my Instruqt environment.

**Comment by scarolan** [comment]
Thanks, Jon.  I've corrected the "File > Open" to read correctly.  Did it look like this?

![image](https://user-images.githubusercontent.com/403332/68892510-cfff0f00-06e8-11ea-92eb-7daae4158766.png)

**Comment by scarolan** [comment]
I'm going to chalk it up to a glitch upstream on the vendor side

**Comment by vaficionado** [comment]
Thanks Sean, that is what it looked like I believe - but the web version of Code has updated slightly in recent days as well. As long as you don't think it's confusing, I'm happy. I don't have access to one of these specific environments to test with anymore 😄
